{
  "hash": "b1326d914577914b715a1186e872fe1b",
  "result": {
    "engine": "knitr",
    "markdown": "# The Solar System from JPL Elements {#sec-solar-system}\n\n\n\nPart II built the tools. Part III uses them. This chapter takes the one system everyone knows, asks where the package's numbers for it come from, and then uses a single long run to do three pieces of real astronomy: verify Kepler's third law across all eight planets and weigh the Sun with it, measure how often Earth and Mars line up, and watch the Sun wobble under Jupiter's pull in the way that lets astronomers find planets around other stars.\n\n## One call\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsolar <- load_solar_system(moon = FALSE, pluto = FALSE) |>\n  simulate_system(time_step = seconds_per_day, duration = seconds_per_year * 170)\n\nsolar |> count(id)\n#> # A tibble: 9 × 2\n#>   id          n\n#>   <chr>   <int>\n#> 1 Earth   62093\n#> 2 Jupiter 62093\n#> 3 Mars    62093\n#> 4 Mercury 62093\n#> 5 Neptune 62093\n#> 6 Saturn  62093\n#> 7 Sun     62093\n#> 8 Uranus  62093\n#> 9 Venus   62093\n```\n:::\n\n\nNine bodies for 170 years at a daily step: a little over half a million rows, which takes a minute or so (Chapter 15 explains where the time goes). The run is long because Neptune's period is 165 years and I want to measure it. The Moon is left out because a daily step is far too coarse for it (Chapter 5), and Pluto because it would need another century.\n\nEvery planet starts at perihelion, which is the package's default, so the planets begin lined up along their individual perihelion directions rather than where they were on any real date. Chapter 7 showed how to fix that with Kepler's equation if you need to; for the measurements below it does not matter.\n\n## Where the numbers come from\n\nThe elements behind `add_planet()` are from JPL's DE440 planetary ephemeris [@park2021]. An ephemeris is not a theory; it is a fit. JPL integrates the full equations of motion of the solar system, including general relativity, the oblateness of the Sun and planets, hundreds of asteroids, and the Moon's own rotation, and adjusts the initial conditions and masses until the model matches every observation they have: centuries of optical astrometry, decades of radar ranging to the inner planets, laser ranging to the Moon, and tracking data from every spacecraft that has flown past or orbited a planet. The result is positions good to well under a kilometer for the inner planets, and the masses in @sec-constants are by-products of the same fit.\n\nWhat the package takes from DE440 is the *osculating* elements of each planet at one instant, the J2000 epoch (noon on January 1, 2000, in Terrestrial Time), in the ecliptic frame of that date. Those elements describe the ellipse each planet was on at that instant. From there orbitr integrates point-mass Newtonian gravity, nothing else. Over the years and decades the planets' orbits stay very close to the real ones; over centuries the effects JPL includes and orbitr does not (relativity for Mercury, the asteroids for Mars) accumulate to differences you could detect with a telescope but not by eye.\n\n## Kepler's third law, verified\n\nChapter 4 derived $T = 2\\pi\\sqrt{a^3/\\mu}$ for one planet. Kepler's version, that $T^2/a^3$ is the same for all planets, is the statement that $\\mu$ is the same for all of them, which it is to the extent that every planet's mass is negligible against the Sun's. Let's measure it. For each planet, the osculating elements at the start give $a$, and `measure_period()` gives $T$:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nplanets <- c(\"Mercury\", \"Venus\", \"Earth\", \"Mars\",\n             \"Jupiter\", \"Saturn\", \"Uranus\", \"Neptune\")\n\nkepler3 <- bind_rows(lapply(planets, function(p) {\n  get_orbital_elements(solar, p, \"Sun\", mu = gravitational_constant * mass_sun)[1, ] |>\n    mutate(planet = p,\n           T_days = measure_period(solar, p, \"Sun\") / seconds_per_day)\n})) |>\n  select(planet, a, e, T_days)\n\nkepler3\n#> # A tibble: 8 × 4\n#>   planet        a       e  T_days\n#>   <chr>     <dbl>   <dbl>   <dbl>\n#> 1 Mercury 5.79e10 0.206      88.2\n#> 2 Venus   1.08e11 0.00680   225. \n#> 3 Earth   1.50e11 0.0167    365. \n#> 4 Mars    2.28e11 0.0934    687. \n#> 5 Jupiter 7.78e11 0.0489   4329. \n#> 6 Saturn  1.43e12 0.0565  10786. \n#> 7 Uranus  2.87e12 0.0457  30795. \n#> 8 Neptune 4.49e12 0.0113  59514.\n```\n:::\n\n\nMercury's 88 days and Neptune's 165 years come out of the same run. On a log-log plot, $T$ against $a$ should be a straight line of slope $3/2$:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nfit <- lm(log(T_days) ~ log(a), data = kepler3)\n\nkepler3 |>\n  ggplot(aes(a / distance_earth_sun, T_days / 365.25)) +\n  geom_abline(intercept = 0, slope = 1.5, color = \"grey60\") +   # T = a^(3/2) in AU and years\n  geom_point() +\n  geom_text(aes(label = planet), hjust = -0.2, vjust = 0.3, size = 3) +\n  scale_x_log10() + scale_y_log10() +\n  labs(x = \"Semi-major axis (AU)\", y = \"Period (years)\")\n```\n\n::: {.cell-output-display}\n![Orbital period against semi-major axis for the eight planets, from the simulation. The line has slope exactly $3/2$.](08-the-solar-system_files/figure-html/fig-kepler3-1.png){#fig-kepler3 fig-align='center' width=100%}\n:::\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncoef(fit)[[\"log(a)\"]]\n#> [1] 1.498288\n```\n:::\n\n\nThat is the exponent. Now the constant. Rearranging, $\\mu = 4\\pi^2 a^3/T^2$, and $\\mu/G$ is a mass:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nkepler3 |>\n  mutate(M_implied = 4 * pi^2 * a^3 / (T_days * seconds_per_day)^2 /\n                     gravitational_constant,\n         M_over_sun = M_implied / mass_sun) |>\n  select(planet, M_over_sun)\n#> # A tibble: 8 × 2\n#>   planet  M_over_sun\n#>   <chr>        <dbl>\n#> 1 Mercury      0.994\n#> 2 Venus        0.999\n#> 3 Earth        1.000\n#> 4 Mars         1.000\n#> 5 Jupiter      1.00 \n#> 6 Saturn       1.01 \n#> 7 Uranus       0.994\n#> 8 Neptune      1.02\n```\n:::\n\n\nEvery planet weighs the Sun. The answers agree to better than a part in a thousand, and the one that disagrees most is Jupiter, because what the period really measures is $M_\\odot + m_{\\mathrm{planet}}$, and Jupiter is a thousandth of a solar mass. Kepler had no way to know that his third law was slightly different for each planet; the differences were far below the precision of Tycho's data. We can see them in a table.\n\n::: {.callout-note title=\"Where it comes from\"}\nThis is exactly how the masses in @sec-constants were determined, with one twist. For a planet with moons, you watch a moon: its period and distance give $G(M_{\\mathrm{planet}} + m_{\\mathrm{moon}})$ directly. Jupiter's mass was known to a fraction of a percent by the 18th century from the Galilean moons, long before anyone had a good value of $G$, which is why astronomers habitually quote $GM$ rather than $M$. For Mercury and Venus, which have no moons, the mass had to wait for spacecraft: the bending of a spacecraft's path during a flyby is a two-body hyperbola, and Chapter 4's formulas give the mass from the deflection.\n:::\n\n## How often do Earth and Mars line up?\n\nMars is closest to Earth, and brightest in our sky, at *opposition*, when Earth passes between Mars and the Sun, so that the two planets have the same heliocentric longitude. How often does that happen? Earth laps Mars, and the time between lappings, the *synodic period*, follows from the angular rates. Earth's longitude advances at $2\\pi/T_E$ per unit time and Mars's at $2\\pi/T_M$, so the difference advances at $2\\pi(1/T_E - 1/T_M)$, and one full lap takes\n\n$$\n\\frac{1}{T_{\\mathrm{syn}}} = \\frac{1}{T_E} - \\frac{1}{T_M}.\n$$ {#eq-synodic}\n\nWith the measured periods:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nT_E <- kepler3$T_days[kepler3$planet == \"Earth\"]\nT_M <- kepler3$T_days[kepler3$planet == \"Mars\"]\n1 / (1 / T_E - 1 / T_M)\n#> [1] 780.2493\n```\n:::\n\n\nAbout 780 days, or two years and seven weeks. Now from the data directly. Compute each planet's heliocentric longitude, unwrap it so it grows continuously, and take the difference:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlongitude <- function(sim, body) {\n  relative_state(sim, body, \"Sun\") |>\n    transmute(time, lambda = unwrap(atan2(ry, rx)))\n}\n\nlap <- inner_join(longitude(solar, \"Earth\"), longitude(solar, \"Mars\"),\n                  by = \"time\", suffix = c(\"_earth\", \"_mars\")) |>\n  mutate(lead = lambda_earth - lambda_mars)\n```\n:::\n\n\nThe lead grows by $2\\pi$ per synodic period, so its average slope gives $T_{\\mathrm{syn}}$ directly:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nslope <- coef(lm(lead ~ time, data = lap))[[\"time\"]]\n2 * pi / slope / seconds_per_day\n#> [1] 780.2043\n```\n:::\n\n\nThe two agree. But the lead does not grow uniformly. The times when it passes a multiple of $2\\pi$ are the oppositions:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\noppositions <- lap |>\n  filter(floor(lead / (2 * pi)) != lag(floor(lead / (2 * pi)))) |>\n  pull(time) / seconds_per_day\n\nhead(diff(oppositions), 8)\n#> [1] 783 809 799 775 767 764 767 777\n```\n:::\n\n\nThe gaps between successive oppositions swing from about 764 to 810 days. The reason is Mars's eccentricity: it moves faster near perihelion and slower near aphelion, so Earth catches it sooner or later depending on where in its orbit the catching happens. Oppositions near Mars's perihelion are also the close ones, when Mars is at its largest and brightest in our sky; they recur every 15 to 17 years, and the synodic period alone does not tell you that. The simulation does.\n\n## The Sun wobbles\n\nThe Sun is not fixed. Chapter 4's center-of-mass analysis applies to every pair, and Jupiter, a thousandth of a solar mass at 5.2 AU, pulls the Sun around a circle of radius about 0.005 AU, a little more than the Sun's own radius, once every 11.9 years. The Sun's speed on that circle is a dozen meters per second. That number is the foundation of the radial-velocity method for finding planets around other stars: you cannot see the planet, but a spectrograph can see the star's velocity along your line of sight change by meters per second as the planet goes around.\n\n`load_solar_system()` starts the Sun at rest at the origin, so the system's center of mass drifts slowly (Chapter 2 again). To see the wobble alone, look at the Sun in the barycentric frame, where the center of mass is at rest by construction:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsun_wobble <- solar |>\n  shift_reference_frame(\"barycenter\") |>\n  filter(id == \"Sun\")\n```\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsun_wobble |>\n  filter(time < seconds_per_year * 60) |>\n  ggplot(aes(time / seconds_per_year, vx)) +\n  geom_line() +\n  labs(x = \"Years\", y = \"Sun's velocity, x component (m/s)\")\n```\n\n::: {.cell-output-display}\n![The Sun's velocity relative to the solar system's center of mass, $x$ component, over 60 years. The 12-year, 12 m/s oscillation is Jupiter; the slower modulation on top of it is Saturn.](08-the-solar-system_files/figure-html/fig-sun-wobble-1.png){#fig-sun-wobble fig-align='center' width=100%}\n:::\n:::\n\n\nTwelve meters per second is a brisk walking pace, measured on a star. For a distant observer sitting in the plane of the solar system, that is the signal the Sun would show. Modern spectrographs reach below one meter per second, which is enough to find Saturn (about 3 m/s) and, with patience, Neptune. Earth's contribution is nine centimeters per second, which is why finding true Earth twins this way is still at the edge of what is possible.\n\n## A long run checked\n\nA 170-year integration is long enough that it is worth asking whether the integrator held up. The total energy of a nine-body system needs every pair at every time step, which for 62,000 steps and 36 pairs is more rows than we need; sampling every 30 days is plenty for a drift check:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsolar |>\n  filter(time %% (seconds_per_day * 30) == 0) |>\n  conserved_quantities() |>\n  ggplot(aes(time / seconds_per_year, energy_error)) +\n  geom_line() +\n  labs(x = \"Years\", y = \"Relative energy error\")\n```\n\n::: {.cell-output-display}\n![Relative energy error of the 170-year solar system run, sampled every 30 days. The oscillation is Mercury's orbit; there is no drift.](08-the-solar-system_files/figure-html/fig-solar-energy-1.png){#fig-solar-energy fig-align='center' width=100%}\n:::\n:::\n\n\nThe error oscillates at the level set by Mercury, the tightest orbit, and does not grow, which is Chapter 5's promise kept over 62,000 steps. If you double the duration, the band stays the same width. If you double the step, it gets four times wider. Both are worth doing once to see.\n\n::: {.callout-tip title=\"Key results\"}\n- The package's planets are osculating J2000 elements from JPL DE440, integrated with Newtonian point-mass gravity.\n- Kepler's third law holds across all eight planets to better than a part in a thousand; the residual is each planet's own mass.\n- Synodic period: $1/T_{\\mathrm{syn}} = 1/T_1 - 1/T_2$. Earth-Mars: about 780 days, varying by $\\pm 3\\%$ because of Mars's eccentricity.\n- The Sun moves at about 12 m/s because of Jupiter; this is the radial-velocity exoplanet signal.\n:::\n",
    "supporting": [
      "08-the-solar-system_files\\figure-html"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}